// Generated by CoffeeScript 1.7.1
this.Blockchain = (function() {
  function Blockchain() {}

  Blockchain.prototype.create_wallet = function() {
    HTTP.call("GET", "https://blockchain.info/api/v2/create_wallet", {
      content: 'application/x-www-form-urlencoded'
    }, {
      params: {
        password: "example_password",
        api_code: ""
      }
    });
    console.log(response);
    return console.log("I DID IT!");
  };

  return Blockchain;

})();

new Blockchain;
